name: VOT1 Autonomous Improvement

on:
  schedule:
    # Run weekly on Monday at 1:00 AM UTC
    - cron: '0 1 * * 1'
  workflow_dispatch:
    inputs:
      components:
        description: 'Comma-separated list of components to improve (leave empty for auto-discovery)'
        required: false
      create_prs:
        description: 'Create pull requests for improvements'
        type: boolean
        default: true
      only_analyze:
        description: 'Only analyze without making improvements'
        type: boolean
        default: false

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  GITHUB_OWNER: ${{ github.repository_owner }}
  GITHUB_REPO: ${{ github.event.repository.name }}
  VOT1_WORKSPACE_DIR: ${{ github.workspace }}

jobs:
  autonomous-improvement:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          # We need full history for better analysis
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install pytest pytest-asyncio

      - name: Configure Git
        run: |
          git config --global user.name "VOT1 Improvement Bot"
          git config --global user.email "bot@vot1.ai"

      - name: Environment Info
        run: |
          echo "Repository: $GITHUB_OWNER/$GITHUB_REPO"
          echo "Workspace: $VOT1_WORKSPACE_DIR"
          python --version
          pip list

      - name: Run Repository Health Check
        run: |
          python -m scripts.run_github_bridge check-repo-health --create-issue --no-prompt

      - name: Analyze Repository
        if: ${{ github.event_name == 'schedule' || !inputs.only_analyze }}
        run: |
          python -m scripts.run_github_bridge analyze-repo --no-prompt

      - name: Run Autonomous Improvement Cycle
        if: ${{ github.event_name == 'schedule' || !inputs.only_analyze }}
        run: |
          if [ "${{ github.event.inputs.components }}" != "" ]; then
            IFS=',' read -ra COMPONENTS <<< "${{ github.event.inputs.components }}"
            COMPONENT_ARGS=""
            for component in "${COMPONENTS[@]}"; do
              COMPONENT_ARGS+=" \"$component\""
            done
            eval "python -m scripts.run_github_bridge run-autonomous-cycle --no-prompt --components $COMPONENT_ARGS"
          else
            python -m scripts.run_github_bridge run-autonomous-cycle --no-prompt
          fi

      - name: Create Improvements PR (if manually triggered)
        if: ${{ github.event_name == 'workflow_dispatch' && inputs.create_prs && !inputs.only_analyze }}
        run: |
          # Create a branch for improvements
          BRANCH_NAME="autonomous-improvements-$(date +%Y%m%d-%H%M%S)"
          git checkout -b $BRANCH_NAME
          
          # Check if there are changes
          if [[ -z $(git status --porcelain) ]]; then
            echo "No changes to commit"
            exit 0
          fi
          
          # Commit changes
          git add .
          git commit -m "Autonomous improvements by VOT1"
          
          # Push the branch
          git push origin $BRANCH_NAME
          
          # Create a PR
          PR_BODY="This pull request contains autonomous improvements made by VOT1.

## Changes
- Improved code quality
- Enhanced documentation
- Optimized performance
- Fixed potential issues

Please review the changes carefully before merging."
          
          PR_TITLE="Autonomous Improvements by VOT1"
          
          # Use the GitHub CLI to create the PR
          gh pr create --title "$PR_TITLE" --body "$PR_BODY" --base main --head $BRANCH_NAME
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate Improvement Summary
        run: |
          echo "# VOT1 Autonomous Improvement Run" > $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "## Repository" >> $GITHUB_STEP_SUMMARY
          echo "Owner: $GITHUB_OWNER" >> $GITHUB_STEP_SUMMARY
          echo "Repo: $GITHUB_REPO" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          
          if [ "${{ github.event.inputs.components }}" != "" ]; then
            echo "## Target Components" >> $GITHUB_STEP_SUMMARY
            IFS=',' read -ra COMPONENTS <<< "${{ github.event.inputs.components }}"
            for component in "${COMPONENTS[@]}"; do
              echo "- $component" >> $GITHUB_STEP_SUMMARY
            done
          else
            echo "## Mode" >> $GITHUB_STEP_SUMMARY
            echo "Auto-discovery of components to improve" >> $GITHUB_STEP_SUMMARY
          fi
          
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "## Actions Performed" >> $GITHUB_STEP_SUMMARY
          echo "- Repository health check" >> $GITHUB_STEP_SUMMARY
          
          if [ "${{ github.event_name == 'schedule' || !inputs.only_analyze }}" == "true" ]; then
            echo "- Repository analysis" >> $GITHUB_STEP_SUMMARY
            echo "- Autonomous improvement cycle" >> $GITHUB_STEP_SUMMARY
          else
            echo "- Repository analysis only (no improvements made)" >> $GITHUB_STEP_SUMMARY
          fi
          
          if [ "${{ github.event_name == 'workflow_dispatch' && inputs.create_prs && !inputs.only_analyze }}" == "true" ]; then
            echo "- Created pull request with improvements" >> $GITHUB_STEP_SUMMARY
          fi
      
      - name: Upload Analysis Results
        uses: actions/upload-artifact@v3
        with:
          name: vot1-autonomous-improvement-results
          path: |
            memory/
            !memory/**/*.bin
          retention-days: 30 